#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_aisuite = env_modules.Clone()

env_aisuite.AppendUnique(CCFLAGS=['-O2'])


# Thirdparty source files
thirdparty_obj = []

# GGML loader
if env["builtin_aisuite"]:
    thirdparty_dir = "#thirdparty/aisuite"
    env_ai-suit.Prepend(
        CPPPATH=[
            thirdparty_dir,
            thirdparty_dir + "/ggml/include",
        ]
    )

    env_thirdparty = env_aisuite.Clone()
    env_thirdparty.disable_warnings()

    env_thirdparty.Append(CPPPATH=[thirdparty_dir + "/ggml/src"])
    env_thirdparty.add_source_files(thirdparty_obj, thirdparty_dir + "zip.c")



    if env["platform"] == "android":

        env_aisuite.AppendUnique(CPPDEFINES=["XR_OS_ANDROID", "XR_USE_PLATFORM_ANDROID"])

    elif env["platform"] == "linuxbsd":
        env_aisuite.AppendUnique(CPPDEFINES=["XR_OS_LINUX"])

        if env["x11"]:
            env_aisuite.AppendUnique(CPPDEFINES=["XR_USE_PLATFORM_XLIB"])
        if env["wayland"]:
            env_aisuite.AppendUnique(CPPDEFINES=["XR_USE_PLATFORM_WAYLAND"])
        env_aisuite.AppendUnique(CPPDEFINES=["HAVE_SECURE_GETENV"])

    elif env["platform"] == "windows":
        env_aisuite.AppendUnique(CPPDEFINES=["XR_OS_WINDOWS", "NOMINMAX", "XR_USE_PLATFORM_WIN32"])

    elif env["platform"] == "macos":
        env_aisuite.AppendUnique(CPPDEFINES=["XR_OS_APPLE"])

    # add in load
    if env["platform"] != "android":
        # On Android the aisuite_loader is provided by separate plugins for each device
        # Build the engine using object files
        khrloader_obj = []
        env_thirdparty.add_source_files(khrloader_obj, thirdparty_dir + "/src/xr_generated_dispatch_table_core.c")
        env_thirdparty.add_source_files(khrloader_obj, thirdparty_dir + "/src/common/filesystem_utils.cpp")
        env_thirdparty.add_source_files(khrloader_obj, thirdparty_dir + "/src/common/object_info.cpp")
        env_thirdparty.add_source_files(khrloader_obj, thirdparty_dir + "/src/loader/api_layer_interface.cpp")
        env_thirdparty.add_source_files(khrloader_obj, thirdparty_dir + "/src/loader/loader_core.cpp")
        env_thirdparty.add_source_files(khrloader_obj, thirdparty_dir + "/src/loader/loader_instance.cpp")
        env_thirdparty.add_source_files(khrloader_obj, thirdparty_dir + "/src/loader/loader_logger_recorders.cpp")
        env_thirdparty.add_source_files(khrloader_obj, thirdparty_dir + "/src/loader/loader_logger.cpp")
        env_thirdparty.add_source_files(khrloader_obj, thirdparty_dir + "/src/loader/manifest_file.cpp")
        env_thirdparty.add_source_files(khrloader_obj, thirdparty_dir + "/src/loader/runtime_interface.cpp")
        env_thirdparty.add_source_files(khrloader_obj, thirdparty_dir + "/src/loader/xr_generated_loader.cpp")
        env.modules_sources += khrloader_obj



    env.modules_sources += thirdparty_obj


# Godot source files

module_obj = []
env_aisuite.add_source_files(module_obj, "*.cpp")
env.modules_sources += module_obj

env.add_source_files(env.modules_sources, "*.cpp")

Export("env_aisuite")
SConscript("sd/SCsub")

if env.editor_build:
    SConscript("editor/SCsub")

# Needed to force rebuilding the module files when the thirdparty library is updated.
env.Depends(module_obj, thirdparty_obj)
