#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_aisuite")

module_obj = []

env_aisuite.add_source_files(module_obj, "*.cpp")

env.modules_sources += module_obj
